CREATE TABLE public.repositories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_id bigint REFERENCES repositories (id) ON DELETE CASCADE,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    updated_at timestamp WITH time zone,
    name text NOT NULL,
    path text NOT NULL,
    CONSTRAINT pk_repositories PRIMARY KEY (id),
    CONSTRAINT uq_repositories_path UNIQUE (path),
    CONSTRAINT ck_repositories_name_length CHECK ((char_length(name) <= 255)),
    CONSTRAINT ck_repositories_path_length CHECK ((char_length(path) <= 255))
);

CREATE TABLE public.media_types (
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    media_type text NOT NULL,
    CONSTRAINT pk_media_types PRIMARY KEY (id),
    CONSTRAINT uq_media_types_type UNIQUE (media_type),
    CONSTRAINT ck_media_types_type_length CHECK ((char_length(media_type) <= 255))
);

CREATE TABLE public.blobs (
    size bigint NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    media_type_id smallint NOT NULL REFERENCES media_types (id),
    digest bytea NOT NULL,
    CONSTRAINT pk_blobs PRIMARY KEY (digest),
)
PARTITION BY HASH (digest);

CREATE TABLE public.repository_blobs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint NOT NULL REFERENCES repositories (id) ON DELETE CASCADE,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    blob_digest bytea NOT NULL REFERENCES blobs (digest) ON DELETE CASCADE,
    CONSTRAINT pk_repository_blobs PRIMARY KEY (repository_id, id),
    CONSTRAINT uq_repository_blobs_repository_id_blob_digest UNIQUE (repository_id, blob_digest)
)
PARTITION BY HASH (repository_id);

CREATE TABLE public.manifests (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint NOT NULL REFERENCES repositories (id) ON DELETE CASCADE,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    schema_version smallint NOT NULL,
    media_type_id smallint NOT NULL REFERENCES media_types (id),
    configuration_media_type_id smallint REFERENCES media_types (id),
    configuration_payload bytea,
    configuration_blob_digest bytea REFERENCES blobs (digest),
    digest bytea NOT NULL,
    payload bytea NOT NULL,
    CONSTRAINT pk_manifests PRIMARY KEY (repository_id, id),
    CONSTRAINT uq_manifests_repository_id_digest UNIQUE (repository_id, digest)
)
PARTITION BY HASH (repository_id);

CREATE TABLE public.manifest_references (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint NOT NULL,
    parent_id bigint NOT NULL,
    child_id bigint NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_manifest_references PRIMARY KEY (repository_id, id),
    CONSTRAINT fk_manifest_references_repository_id_parent_id_manifests FOREIGN KEY (repository_id, parent_id) REFERENCES manifests (repository_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_manifest_references_repository_id_child_id_manifests FOREIGN KEY (repository_id, child_id) REFERENCES manifests (repository_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_manifest_references_repository_id_parent_id_child_id UNIQUE (repository_id, parent_id, child_id),
    CONSTRAINT ck_manifest_references_parent_id_child_id_differ CHECK (parent_id <> child_id)
)
PARTITION BY HASH (repository_id);

CREATE TABLE public.layers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint NOT NULL,
    manifest_id bigint NOT NULL,
    size bigint NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    media_type_id smallint NOT NULL REFERENCES media_types (id),
    digest bytea NOT NULL REFERENCES blobs (digest),
    CONSTRAINT pk_layers PRIMARY KEY (repository_id, id),
    CONSTRAINT fk_layers_repository_id_manifest_id_manifests FOREIGN KEY (repository_id, manifest_id) REFERENCES manifests (repository_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_layers_repository_id_manifest_id_digest UNIQUE (repository_id, manifest_id, digest)
)
PARTITION BY HASH (repository_id);

CREATE TABLE public.tags (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint NOT NULL,
    manifest_id bigint NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    updated_at timestamp WITH time zone,
    name text NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (repository_id, id),
    CONSTRAINT fk_tags_repository_id_manifest_id_manifests FOREIGN KEY (repository_id, manifest_id) REFERENCES manifests (repository_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_tags_repository_id_name UNIQUE (repository_id, name),
    CONSTRAINT ck_tags_name_length CHECK ((char_length(name) <= 255))
)
PARTITION BY HASH (repository_id);

CREATE TABLE public.blobs_layers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint NOT NULL,
    layer_id bigint NOT NULL,
    digest bytea NOT NULL REFERENCES blobs (digest) ON DELETE CASCADE,
    CONSTRAINT pk_blobs_layers PRIMARY KEY (digest, id),
    CONSTRAINT fk_blobs_layers_repository_id_layer_id_layers FOREIGN KEY (repository_id, layer_id) REFERENCES layers (repository_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_blobs_layers_digest_layer_id UNIQUE (digest, layer_id)
)
PARTITION BY HASH (digest);

CREATE TABLE public.blobs_configurations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint NOT NULL,
    manifest_id bigint NOT NULL,
    digest bytea NOT NULL REFERENCES blobs (digest) ON DELETE CASCADE,
    CONSTRAINT pk_blobs_configurations PRIMARY KEY (digest, id),
    CONSTRAINT fk_blobs_configurations_repository_id_manifest_id_manifests FOREIGN KEY (repository_id, manifest_id) REFERENCES manifests (repository_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_blobs_configurations_digest_layer_id UNIQUE (digest, manifest_id)
)
PARTITION BY HASH (digest);

CREATE TABLE public.tmp_blobs_manifests (
    digest bytea NOT NULL,
    CONSTRAINT pk_tmp_blobs_manifests PRIMARY KEY (digest)
);

CREATE TABLE public.blob_review_queue (
    review_after timestamp with time zone NOT NULL DEFAULT now() + interval '1 day',
    review_count integer NOT NULL DEFAULT 0,
    digest bytea NOT NULL PRIMARY KEY
);

CREATE SCHEMA partitions;

SET search_path = partitions;

CREATE TABLE blobs_default PARTITION OF public.blobs
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

CREATE TABLE repository_blobs_default PARTITION OF public.repository_blobs
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

CREATE TABLE manifests_default PARTITION OF public.manifests
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

CREATE TABLE layers_default PARTITION OF public.layers
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

CREATE TABLE manifest_references_default PARTITION OF public.manifest_references
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

CREATE TABLE tags_default PARTITION OF public.tags
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

CREATE TABLE blobs_layers_default PARTITION OF public.blobs_layers
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

CREATE TABLE blobs_configurations_default PARTITION OF public.blobs_configurations
FOR VALUES WITH (MODULUS 1, REMAINDER 0);

SET search_path = public;
