package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20201019155113_create_manifest_layers_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS manifest_layers (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                manifest_id bigint NOT NULL,
                blob_digest bytea NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                CONSTRAINT pk_manifest_layers PRIMARY KEY (id),
                CONSTRAINT fk_manifest_layers_manifest_id_manifests FOREIGN KEY (manifest_id) REFERENCES manifests (id) ON DELETE CASCADE,
                CONSTRAINT fk_manifest_layers_blob_digest_blobs FOREIGN KEY (blob_digest) REFERENCES blobs (digest) ON DELETE CASCADE,
                CONSTRAINT uq_manifest_layers_manifest_id_blob_digest UNIQUE (manifest_id, blob_digest)
            )`,
			"CREATE INDEX IF NOT EXISTS ix_manifest_layers_manifest_id ON manifest_layers (manifest_id)",
			"CREATE INDEX IF NOT EXISTS ix_manifest_layers_blob_digest ON manifest_layers (blob_digest)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_manifest_layers_blob_digest CASCADE",
			"DROP INDEX IF EXISTS ix_manifest_layers_manifest_id CASCADE",
			"DROP TABLE IF EXISTS manifest_layers CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
