package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20201019155015_create_blobs_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS blobs (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                size bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                marked_at timestamp WITH time zone,
                digest bytea NOT NULL,
                media_type_id smallint NOT NULL,
                CONSTRAINT pk_blobs PRIMARY KEY (id),
                CONSTRAINT fk_blobs_media_type_id_media_types FOREIGN KEY (media_type_id) REFERENCES media_types (id),
                CONSTRAINT uq_blobs_digest UNIQUE (digest)
            )`,
		},
		Down: []string{
			"DROP TABLE IF EXISTS blobs CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
