package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20201019155037_create_configurations_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS configurations (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                blob_digest bytea NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                payload bytea NOT NULL,
                CONSTRAINT pk_configurations PRIMARY KEY (id),
                CONSTRAINT fk_configurations_blob_digest_blobs FOREIGN KEY (blob_digest) REFERENCES blobs (digest) ON DELETE CASCADE,
                CONSTRAINT uq_configurations_blob_digest UNIQUE (blob_digest)
            )`,
			"CREATE INDEX IF NOT EXISTS ix_configurations_blob_digest ON configurations (blob_digest)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_configurations_blob_digest CASCADE",
			"DROP TABLE IF EXISTS configurations CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
