package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20201019155113_create_layers_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS layers (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                manifest_id bigint NOT NULL,
				size bigint NOT NULL,
				created_at timestamp WITH time zone NOT NULL DEFAULT now(),
				media_type_id smallint NOT NULL,
				digest bytea NOT NULL,
                CONSTRAINT pk_layers PRIMARY KEY (id),
                CONSTRAINT fk_layers_manifest_id_manifests FOREIGN KEY (manifest_id) REFERENCES manifests (id) ON DELETE CASCADE,
    			CONSTRAINT fk_layers_media_type_id_media_types FOREIGN KEY (media_type_id) REFERENCES media_types (id),
    			CONSTRAINT fk_layers_digest_blobs FOREIGN KEY (digest) REFERENCES blobs (digest),
                CONSTRAINT uq_layers_manifest_id_digest UNIQUE (manifest_id, digest)
            )`,
			"CREATE INDEX IF NOT EXISTS ix_layers_manifest_id ON layers (manifest_id)",
			"CREATE INDEX IF NOT EXISTS ix_layers_digest ON layers (digest)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_layers_digest CASCADE",
			"DROP INDEX IF EXISTS ix_layers_manifest_id CASCADE",
			"DROP TABLE IF EXISTS layers CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
