CREATE TABLE IF NOT EXISTS manifest_list_manifests
(
    id         bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_id  bigint                   NOT NULL,
    child_id   bigint                   NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_manifest_list_manifests PRIMARY KEY (id),
    CONSTRAINT fk_manifest_list_manifests_parent_id_manifests FOREIGN KEY (parent_id)
        REFERENCES manifests (id) ON DELETE CASCADE,
    CONSTRAINT fk_manifest_list_manifests_child_id_manifests FOREIGN KEY (child_id)
        REFERENCES manifests (id) ON DELETE CASCADE,
    CONSTRAINT uq_manifest_list_manifests_parent_id_child_id UNIQUE (parent_id, child_id),
    CONSTRAINT ck_manifest_list_manifests_parent_id_child_id_not_equal CHECK (child_id <> parent_id)
);