package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &Migration{
		Migration: &migrate.Migration{
			Id: "20210503145024_create_namespaces_table",
			Up: []string{
				`CREATE TABLE IF NOT EXISTS namespaces (
				  	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				  	created_at timestamp WITH time zone NOT NULL DEFAULT now(),
				  	updated_at timestamp WITH time zone,
				  	name text NOT NULL,
				  	CONSTRAINT pk_namespaces PRIMARY KEY (id),
				  	CONSTRAINT unique_namespaces_name UNIQUE (name),
				  	CONSTRAINT check_namespaces_name_length CHECK ((char_length(name) <= 255))
				)`,
			},
			Down: []string{
				"DROP TABLE IF EXISTS namespaces CASCADE",
			},
		},
		PostDeployment: false,
	}

	allMigrations = append(allMigrations, m)
}
