package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &Migration{
		Migration: &migrate.Migration{
			Id: "20210503152740_create_gc_blobs_layers_table",
			Up: []string{
				`CREATE TABLE IF NOT EXISTS gc_blobs_layers (
					id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
					top_level_namespace_id bigint NOT NULL,
					repository_id bigint NOT NULL,
					layer_id bigint NOT NULL,
					digest bytea NOT NULL,
					CONSTRAINT pk_gc_blobs_layers PRIMARY KEY (digest, id),
					CONSTRAINT fk_gc_blobs_layers_digest_repository_id_and_layer_id_layers FOREIGN KEY (digest, top_level_namespace_id, repository_id, layer_id) REFERENCES layers (digest, top_level_namespace_id, repository_id, id) ON DELETE CASCADE,
					CONSTRAINT fk_gc_blobs_layers_digest_blobs FOREIGN KEY (digest) REFERENCES blobs (digest) ON DELETE CASCADE,
					CONSTRAINT unique_gc_blobs_layers_digest_and_layer_id UNIQUE (digest, layer_id)
				)
				PARTITION BY HASH (digest)`,
				"CREATE INDEX IF NOT EXISTS index_gc_blobs_layers_on_dgst_tp_lvl_nmspc_id_rpstry_id_lyr_id ON gc_blobs_layers USING btree (digest, top_level_namespace_id, repository_id, layer_id)",
			},
			Down: []string{
				"DROP INDEX IF EXISTS index_gc_blobs_layers_on_dgst_tp_lvl_nmspc_id_rpstry_id_lyr_id CASCADE",
				"DROP TABLE IF EXISTS gc_blobs_layers CASCADE",
			},
		},
		PostDeployment: false,
	}

	allMigrations = append(allMigrations, m)
}
